// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Core from "@aws-amplify/core";

function configure(config) {
  Core.default.configure(config);
  return /* () */0;
}

export {
  configure ,
  
}
/* @aws-amplify/core Not a pure module */
