// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Core from "@aws-amplify/core";

function configure(config) {
  Core.default.configure(config);
  return /* () */0;
}

var Authenticator = { };

var SignIn = { };

export {
  configure ,
  Authenticator ,
  SignIn ,
  
}
/* @aws-amplify/core Not a pure module */
