// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Theme from "../Theme.bs.js";
import * as ReactNative from "react-native";
import * as AmplifyTheme from "aws-amplify-react-native";

var buttonBackgroundColor = {
  backgroundColor: Theme.Colors.primaryLight
};

var newButton = ReactNative.StyleSheet.flatten(/* array */[
      AmplifyTheme.AmplifyTheme.button,
      buttonBackgroundColor
    ]);

AmplifyTheme.AmplifyTheme.button = newButton;

var buttonDisabledColor = {
  backgroundColor: Theme.Colors.primaryOpaque("0.6")
};

var newButtonDisabled = ReactNative.StyleSheet.flatten(/* array */[
      AmplifyTheme.AmplifyTheme.buttonDisabled,
      buttonDisabledColor
    ]);

AmplifyTheme.AmplifyTheme.buttonDisabled = newButtonDisabled;

var sectionFooterColor = {
  color: Theme.Colors.primaryLight
};

var newSectionFooterLink = ReactNative.StyleSheet.flatten(/* array */[
      AmplifyTheme.AmplifyTheme.sectionFooterLink,
      sectionFooterColor
    ]);

AmplifyTheme.AmplifyTheme.sectionFooterLink = newSectionFooterLink;

var theme = AmplifyTheme.AmplifyTheme;

export {
  buttonBackgroundColor ,
  newButton ,
  buttonDisabledColor ,
  newButtonDisabled ,
  sectionFooterColor ,
  newSectionFooterLink ,
  theme ,
  
}
/* newButton Not a pure module */
