// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Api from "@aws-amplify/api";
import * as Index from "@aws-amplify/pubsub/lib-esm/index";

function configure(config) {
  Api.default.configure(config);
  Index.default.configure(config);
  return /* () */0;
}

var Types = /* alias */0;

export {
  Types ,
  configure ,
  
}
/* @aws-amplify/api Not a pure module */
