// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function levelToString(param) {
  switch (param) {
    case /* Error */0 :
        return "ERROR";
    case /* Warn */1 :
        return "WARN";
    case /* Info */2 :
        return "INFO";
    case /* Verbose */3 :
        return "VERBOSE";
    case /* Debug */4 :
        return "DEBUG";
    case /* Silly */5 :
        return "SILLY";
    
  }
}

function fromJsAttrs(attributes) {
  return {
          sub: attributes.sub,
          email_verified: attributes.email_verified,
          email: attributes.email,
          phone_number: attributes.phone_number
        };
}

function fromJs(data) {
  return {
          username: data.username,
          attributes: fromJsAttrs(data.attributes)
        };
}

function commentToRecord(data) {
  return {
          id: data.id,
          talkId: data.talkId,
          message: data.message,
          createdAt: data.createdAt,
          createdBy: data.createdBy,
          deviceId: data.deviceId
        };
}

export {
  levelToString ,
  fromJsAttrs ,
  fromJs ,
  commentToRecord ,
  
}
/* No side effect */
