// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Auth from "./Auth.bs.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as PromiseMonad from "bs-promise-monad/src/PromiseMonad.bs.js";

var user = {
  username: "",
  email: "",
  phone_number: "",
  jwtToken: ""
};

function getName(param) {
  return user.username;
}

function getPhone(param) {
  return user.phone_number;
}

function getEmail(param) {
  return user.email;
}

function getToken(param) {
  return user.jwtToken;
}

var setSession = PromiseMonad.$great$great$eq(Auth.getCurrentAuthUser(/* () */0), (function (response) {
        var jwtToken = Belt_Option.getWithDefault(Belt_Option.flatMap(Belt_Option.flatMap(response.signInUserSession, (function (session) {
                        return session.accessToken;
                      })), (function (accessToken) {
                    return accessToken.jwtToken;
                  })), "");
        var email = Belt_Option.getWithDefault(Belt_Option.flatMap(Belt_Option.flatMap(Belt_Option.flatMap(response.signInUserSession, (function (session) {
                            return session.idToken;
                          })), (function (idToken) {
                        return idToken.payload;
                      })), (function (payload) {
                    return payload.email;
                  })), "");
        var phone_number = Belt_Option.getWithDefault(Belt_Option.flatMap(Belt_Option.flatMap(Belt_Option.flatMap(response.signInUserSession, (function (session) {
                            return session.idToken;
                          })), (function (idToken) {
                        return idToken.payload;
                      })), (function (payload) {
                    return payload.phone_number;
                  })), "");
        var username = Belt_Option.getWithDefault(response.username, "");
        user.username = username;
        user.email = email;
        user.phone_number = phone_number;
        user.jwtToken = jwtToken;
        return PromiseMonad.$$return(user);
      }));

export {
  user ,
  getName ,
  getPhone ,
  getEmail ,
  getToken ,
  setSession ,
  
}
/* setSession Not a pure module */
