// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as UserContext from "./UserContext.bs.js";
import * as AmplifyTheme from "../aws/AmplifyTheme.bs.js";
import * as AppNavigator from "../AppNavigator.bs.js";
import * as AwsAmplifyReactNative from "aws-amplify-react-native";

function makeProps(prim, prim$1) {
  var tmp = { };
  if (prim !== undefined) {
    tmp.key = Caml_option.valFromOption(prim);
  }
  return tmp;
}

var make = AwsAmplifyReactNative.withAuthenticator(AppNavigator.make, AmplifyTheme.theme);

var Authenticator = {
  makeProps: makeProps,
  make: make
};

function Authenticated(Props) {
  var children = Props.children;
  var match = UserContext.useUser(/* () */0);
  return React.createElement(React.Fragment, undefined, match[0] ? children : React.createElement(make, { }));
}

var make$1 = Authenticated;

var $$default = Authenticated;

export {
  Authenticator ,
  make$1 as make,
  $$default ,
  $$default as default,
  
}
/* make Not a pure module */
