// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as UserContext from "./UserContext.bs.js";

var make = UserContext.context.Provider;

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

export {
  make ,
  makeProps ,
  
}
/* make Not a pure module */
