// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";

function checkAuthWithRoute(navigation) {
  return ReactNative.AsyncStorage.getItem("userToken").then((function (stringOrNull) {
                console.log("CHECKING_AUTH_TOKEN", stringOrNull);
                if (stringOrNull !== null) {
                  return Promise.resolve((navigation.navigate("App"), /* () */0));
                } else {
                  return Promise.resolve((navigation.navigate("SignIn"), /* () */0));
                }
              }));
}

function signOutAsync(navigation) {
  ReactNative.AsyncStorage.clear().then((function (_result) {
          return Promise.resolve(Promise.resolve((navigation.navigate("AuthLoading"), /* () */0)));
        }));
  return /* () */0;
}

function signInAsync(navigation) {
  ReactNative.AsyncStorage.setItem("userToken", "abc").then((function (_result) {
          return Promise.resolve(Promise.resolve((navigation.navigate("App"), /* () */0)));
        }));
  return /* () */0;
}

export {
  checkAuthWithRoute ,
  signOutAsync ,
  signInAsync ,
  
}
/* react-native Not a pure module */
