// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as AppNavigator from "./AppNavigator.bs.js";

var $$default = AppNavigator.make;

export {
  $$default ,
  $$default as default,
  
}
/* AppNavigator Not a pure module */
