// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";

var styles = ReactNative.StyleSheet.create({
      container: {
        alignItems: "center",
        flex: 1,
        justifyContent: "center"
      },
      header: {
        fontSize: 25,
        marginBottom: 5
      }
    });

export {
  styles ,
  
}
/* styles Not a pure module */
