// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Utils from "./utils/Utils.bs.js";
import * as React from "react";
import * as GlobalStyle from "./GlobalStyle.bs.js";
import * as AwsAmplify from "aws-amplify";
import * as ReactNative from "react-native";

function HomeScreen(Props) {
  var navigation = Props.navigation;
  return React.createElement(ReactNative.View, {
              style: GlobalStyle.styles.container,
              children: null
            }, React.createElement(ReactNative.Button, {
                  onPress: (function (param) {
                      navigation.navigate("Other");
                      return /* () */0;
                    }),
                  title: "Show me more of the app"
                }), React.createElement(ReactNative.Button, {
                  onPress: (function (param) {
                      AwsAmplify.Auth.signOut();
                      return Utils.signOutAsync(navigation);
                    }),
                  title: "Actually, sign me out :)"
                }));
}

var make = HomeScreen;

export {
  make ,
  
}
/* Utils Not a pure module */
