// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactNative from "react-native";

function LoadingScreen(Props) {
  var match = Props.countdown;
  var countdown = match !== undefined ? match : 3;
  var navigation = Props.navigation;
  var match$1 = React.useState((function () {
          return countdown;
        }));
  var setCount = match$1[1];
  var count = match$1[0];
  React.useEffect((function () {
          var intervalId = setInterval((function (param) {
                  console.log("count", count);
                  return Curry._1(setCount, (function (count) {
                                return count - 1 | 0;
                              }));
                }), 1000);
          return (function (param) {
                    console.log("Clear Interval");
                    clearInterval(intervalId);
                    return /* () */0;
                  });
        }), ([]));
  React.useEffect((function () {
          if (count === 0) {
            console.log("navigating to Center");
            navigation.navigate("App");
          } else {
            console.log("Navigate to center in: " + (String(count) + ""));
          }
          return ;
        }), [count]);
  return React.createElement(React.Fragment, undefined, React.createElement(ReactNative.View, {
                  style: {
                    alignItems: "center",
                    flex: 1,
                    justifyContent: "center"
                  },
                  children: React.createElement(ReactNative.Text, {
                        children: String(count)
                      })
                }));
}

var make = LoadingScreen;

export {
  make ,
  
}
/* react Not a pure module */
