// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as GlobalStyle from "./GlobalStyle.bs.js";
import * as ReactNative from "react-native";
import * as SignIn from "aws-amplify-react-native/src/Auth/SignIn";

function SignInScreen(Props) {
  Props.navigation;
  return React.createElement(ReactNative.View, {
              style: GlobalStyle.styles.container,
              children: React.createElement(SignIn.SignIn, { })
            });
}

var make = SignInScreen;

export {
  make ,
  
}
/* react Not a pure module */
