// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";

var dimensions = ReactNative.Dimensions.get("window");

function primaryOpaque(opacity) {
  return "rgba(18, 25, 50," + (opacity + ")");
}

var Colors = {
  primary: "rgba(18, 25, 50, 1)",
  primary2: "rgba(27, 37, 77, 1)",
  primaryLight: "rgba(27, 37, 77, 1)",
  primaryDark: "rgba(14, 20, 43, 1)",
  primaryOpaque: primaryOpaque,
  primaryText: "white",
  highlight: "#61dafb"
};

var Typography = {
  primary: "Gotham Rounded",
  secondary: "Gotham Rounded",
  medium: "GothamRnd Medium",
  bold: "Gotham Bold"
};

var primaryText = "white";

export {
  dimensions ,
  primaryText ,
  Colors ,
  Typography ,
  
}
/* dimensions Not a pure module */
